var prose = require("./-prose.template._.js");
module.exports = {
	toString: prose.page,
	meta: meta, type: "story", released: new Date("Sat, 19 Apr 2014 20:51:00 GMT"),
	title: "Fall",
	blurb: "Velt plummets through the atmosphere, clutching the ancient tome that he risked his life to acquire.",
	content: [
		prose (_/*
			Jamie sat on the wooden bench on the edge of the quad, watching the last few stragglers cut through the grass to the main gate in the opposite corner. Two students lurched a ball between them, one telekinetically pushing it back to the other as it fell towards them in the air, the other lurching it back. They seemed so happy—to be here, to hone their abilities… Jamie didn’t have any of that.
			He often wondered why the school chose him in the first place. He clearly had no talent with the gift. He barely qualified as a Telkin at all. How could he be expected to keep up with the class when he couldn’t so much as bend a frickin’ spoon?
			He looked back down at the papers in front of him. To the left, a textbook showed graphs and diagrams of how “lurching” applies force to an object from a Telkin’s centre of mass. To the right, sheets of homework asked questions about the ethics of using telekinesis on animate objects. While he found the ethics lessons interesting, he couldn’t deny the futility of it all. With his grades, he’d never make it past this semester, let alone graduation. Unless he could fix it.
			Jamie heard footsteps coming down the concrete path, off to his left. He leaned over his books, hiding his face and trying to look busy. The man walked past and off to the right, paying no attention to the student. <em>Just like in class,</em> Jamie thought. He glanced at the teacher as he turned the corner into the entranceway of the faculty block. Mr. Simmons was off to his office, as expected, and right on time.
			Jamie started packing his papers into his backpack, looking around at the quad, alert for any more students hanging around. Happy he was clear, he stood and began shuffling towards the building entrance, careful not to catch up to Simmons.
			The penalty for getting kicked out of Telekinetic School for the Gifted or failing to graduate was made clear to every student attending. There was even a law: any Telkin that cannot demonstrate control and competency with their power is banned from using it. Of course, what was not explicitly stated in that law was that the “banned” part meant getting neutered. The poor sod would be dragged away and have the part of the brain responsible for their power surgically removed.
			Jamie knew how poorly he was doing in the classes, none so poorly as in Simmons’ torque class, dedicated to developing raw telekinetic strength. He’d already been held back to repeat a semester, and if he didn’t pass this time he’d be expelled for sure. He’d be deemed a danger to society. He’d be neutered. But if everything went according to plan, it wouldn’t get that far.
			He entered the faculty building and started towards Simmons’ office. He was familiar with the building; its rich chestnut panelling, its fraying silk carpets running down the centre of the hallways, its almost sweet musty smell. The smell of defeat, of failure. He’d seen these halls all too often, called for extra lessons and for stern talks about responsibility or “put some damn effort into it, Jamie”.
			He counted off two doors, and slowed as he approached the third. A gold plaque on the door told him he’d found the right one, announcing “Mr. Edward Simmons, Torque Teacher”.
			Jamie felt his heart thump loud in his ears. Was he really going to do this? Once he took this step, there would be no going back. But what else could he do? Swinging his backpack around to the side, he leant back against the smooth wooden wall and sunk to the floor. He had to get comfortable if this was going to work. Silently, he took in a deep breath, closed his eyes, and relaxed.
			He let the universe speak to him, felt for the presence of the people nearby. Slowly, he became aware of the teachers in their offices, some with students sitting across from them taking notes or silently letting the lectures wash over them. And there, just behind him, sat Mr. Simmons. He drew closer to the teacher, brushing by him ever so gently so as to not spook him. Jamie drew in a new breath, held it, and reached out.
			The dark world suddenly burst with light and colour. He found himself looking down at some ledger or other, pen in hand, stopped mid-sentence in an illegible, cramped script. He was in.
			He stood, Simmons’ larger girth wobbling slightly, threatening to unbalance him. Jamie held on, forcefully commanding the teacher’s body to stand firm. It obeyed. He may suck at lurch-ball, but this was his forte. No one in his class could do <em>this</em>. Maybe no one in the <em>world</em> could do this.
			He walked around the large desk, sidling past the square edges and stepping up to the filing cabinet in the opposite corner. Shoving his large, pudgy hands into his pockets, he rifled around, searching for the key. Finally, his fingers brushed against something hard and metallic. Pulling the key out of his pocket, he slid it easily into the filing cabinet lock and turned.
			Jamie stepped back, pulling out the top draw before stretching out his arms and cracking his knuckles, a grin on his face. Simmons would be horrified if he knew. He flicked through the hundreds of files, scanning each name as he went. The cabinet would be full to bursting with files on each student. With such a small percentage of the population having the ability, there were few teachers who had the gift and who knew it well enough themselves to teach others how to use and control the power. Which meant each teacher had to teach every kid in the school, week-in, week-out.
			Baern, Braithwaite… “Brath, James,” he said, Simmons’ older voice crackling in place of his own. He carefully removed the file from the cabinet, laying it flat on top of the others. He hesitated. He didn’t care about grades, graduation, or even getting expelled. Was it too much to ask for everyone to leave him alone? To keep his brain in one piece? Still, forcing a teacher to change his grade without him even knowing… Steeling himself, Jamie reached forward, watching as the teacher’s hairy hand start to slowly open the file.
			A sudden tap on the shoulder snapped him back to the corridor outside. He recoiled from the figure standing over him
			“Now, that’s quite enough of that, son,” the man said, with a warm smile.
			“I don’t—” Jamie said. “I wasn’t— I just dozed off, sir.”
			The man let out a low chuckle. “You can’t fool me, son. So best not try, eh?”
			“What— But I—” Jamie started to push himself up off of the floor, feeling foolish. How did he ever think this would go smoothly? Did anything <em>ever</em> go as planned?
			“What’s your name, son?”
			“Jamie,” the boy said, looking away. “Brath. Sir.”
			“Very well, Brath.” The man looked up and down the corridor, conspiratorially. Who was this guy? Jamie didn’t recognise him as one of the regular teachers. “I tell you what. You don’t try anything so foolhardy as this again, and I’ll help you out.”
			“But I didn’t—”
			“You aren’t the only one in the world that can do what you do, okay?” the man continued. “There are more of us than you realise—than the world realises. But it’s not as simple as it looks, son.” He paused. “Listen, you can take it or leave it, but if you attend some extra lessons with me after school, I can teach you how to use your gifts. Plus, I’ll keep your head above water with Simmons. The <em>right</em> way.” He stuck out a hand and waited for Jamie to take it. “Deal?”
			Jamie eyed the hand. Did this man really know what Jamie was doing? Were there really others like him? Of course, the alternative would be expulsion and neutering. Uncertain, he took the hand and shook it weakly.
			“Who are you, anyway?” he asked, glancing back up at the man.
			“Bartholomew Dorn.” Jamie gave a blank look. “Careers advisor?”
			Jamie snorted a laugh despite himself. Everyone knew there were only two options once you got out of this place: army or police. Not much of a choice.
			“I know, right?” Dorn said with a cheeky grin. “Lots of nothing to do, but the pay’s good. It’s a ‘those that can’t do teach’ kind of a thing. Although I guess it’s more like ‘those who can’t teach, advise’… but whatever. See you tomorrow, then.” He started walk backwards down the corridor. “After class. Don’t forget, now!” Finally, he turned and disappeared around a corner, leaving Jamie alone.
			He felt the eerie silence of the building settle back in around him, the musty smell resuming its hold. <em>More extra lessons,</em> he thought.<em> Great.</em>
		*/)
	]
};